apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: activemq-artemis-scaledobject
  namespace: default
  labels:
    deploymentName: activemqartemis-function
spec:
  scaleTargetRef:
    deploymentName: activemqartemis-function
  triggers:
  - type: activemq-artemis
    metadata:
      # Required
      jolokiaHost: http://admin:adminpw@host:8161
      queueName: myqueue
      # Optional
      queueLength: '5' # Queue length target for HPA. Default: 5 messages
---

